### ISSUE TITLE
参加ゲームルーム選択ページ(/playgame)のページの実装

### ISSUE THREAD

**Issue by e1b22103** [Yura-Mp/quiz_7#47]
⇒ ※Project Status参照．
担当者: 
PR締め切り: 12/25

--------------------------------------------------------------------------------------------

### [前提タスク]
- ゲームルーム公開前準備ページ(/gameroom/prepare_open)のPOSTリクエストに対する処理の実装

### [概要]
- 公開状態のゲームルームを一覧表示し，入室したいゲームルームを選択するためのページのページ(画面，View)実装を行うタスク．

### [やること]
- [x] 以下に示すDoDを満たす内容の実装．

### [DoD]
- [x] 「/playgame」へのGETリクエストにより，このタスクで実装するページが表示されること．
- [x] 公開状態(DB: gameRoom.published が TRUE)**かつ公開ゲームルーム(PublicGameRoomクラス)のクラスとして存在する**~~の~~ゲームルームを一覧表示する構造をもったページであること．
- [x] 一覧表示されたゲームルームそれぞれに，ゲームルーム名(頭20文字まで)，ホスト名(頭20文字まで)，最大参加人数，参加ゲームルーム入室確認ページ(/playgame/join_check)に遷移する「選択」ボタンが表示されていること．
- [x] 公開ゲームルームが表示エリアに収まらない場合，スクロールバーが表示されること．
- [x] ~~ゲームルーム管理ページ(/gameroom)に遷移する「戻る」ボタンが存在すること．~~
- [x] [修正] メインページ(/main)に遷移する「戻る」ボタンが存在すること

### [備考]
　一覧表示されたゲームルームそれぞれに，「現在参加人数 / 最大参加人数」のような表示があると参加できるかどうかわかりやすいが，現状だと現在参加人数を確認する部分を実装できていないため，後のタスクで改めて表示部分を改良するべきである．

**Comment by Yura-Mp** [comment]
[DoD] に「_/playgame_へのGETリクエストでこのタスクで実装するページが表示されること」というような項目が欲しいように思います．

**Comment by M02630124** [comment]
今この部分の実装を考えているんですが、このページで一覧表示する PublicGameRoom は、ルーム名やホスト名を直接には持っていません。IDを見てDBから引っ張ってくることはできるのですが、Thymeleaf でページにマッピングするのが難しそうです（1ルームだけなら別々にマッピングもできますが、th:each を使うなら1つのオブジェクトにまとまっていないと対応付けられないので）。

@Yura-Mp が実装してくれた部分の変更になりますが、PublicGameRoom にルーム名やホスト名のフィールドも持たせる方がいいかもしれません。確か以前に自分が意見して削った部分なので申し訳ないですが、そのように変更していいでしょうか？

**Comment by Yura-Mp** [comment]
@e1b22061 

　返信遅れて申し訳ありません．提案して頂いた手法で解決してもらって結構です．

　一応，PublicGameRoomクラスのIDからDBを引っ張ってきて，これをth:eachに反映する手法を提案します．(正しいかどうかはわからん)
1. DBMapperで公開状態のゲームルームをGameRoomクラスの配列で取得する．
2. その配列をModelMapでth:eachする属性に追加する．
3. (htmlページ側)th:eachで展開されるGameRoomクラスのデータから，必要なフィールドを指定して表示させる．
上記の方法でできない可能性があるので，鵜吞みにはしないでください．
