### ISSUE TITLE
参加ゲームルーム入室確認ページ(/playgame/join_check)のページの実装

### ISSUE THREAD

**Issue by e1b22103** [Yura-Mp/quiz_7#48]
⇒ ※Project Status参照．
担当者: Yura-Mp
PR締め切り: 12/26(木) ~~19:00~~ 22:00 (12/26変更)

--------------------------------------------------------------------------------------------

### [前提タスク]
- 参加ゲームルーム選択ページ(/playgame)のページの実装

### [概要]
- 入室したいゲームルームを選択した後に，該当ゲームルームの詳細を表示し，本当に入室するか確認するためのページのページ(画面，View)実装を行うタスク．

### [やること]
- [ ] 以下に示すDoDを満たす内容の実装．

### [DoD]
- [ ] 「/playgame/join_check」へのGETリクエストにより，このタスクで実装するページが表示されること．
- [ ] 選択したゲームルームに入室するかを問う文言と，ゲームルーム参加者開始前ページ(/playgame/standby)に遷移する「入室」ボタンが存在すること．
- [ ] 選択したゲームルームについて，以下の情報が表示されること．
  - [ ] ゲームルームの名前．(DB: gameRoom.roomName)
  - [ ] ゲームルームの説明．(DB: gameRoom.description)
  - [ ] ホストユーザ名．
  - [ ] 最大参加人数．
- [ ] 参加ゲームルーム選択ページ(/playgame)に遷移する「戻る」ボタンが存在すること．

### [備考]
　「現在参加人数 / 最大参加人数」のような表示があると参加できるかどうかわかりやすいが，現状だと現在参加人数を確認する部分を実装できていないため，後のタスクで改めて表示部分を改良するべきである．

**Comment by Yura-Mp** [comment]
[DoD] に「_/playgame/join_check_へのGETリクエストでこのタスクで実装するページが表示されること」というような項目が欲しいように思います．
