### ISSUE TITLE
参加ゲームルーム入室確認ページ(/playgame/join_check)のPOSTリクエストに対する処理の実装

### ISSUE THREAD

**Issue by e1b22103** [Yura-Mp/quiz_7#52]
⇒ ※Project Status参照．
担当者: Yura-Mp
PR締め切り: 12/26(木) ~~19:00~~ 22:00 (12/26変更)

--------------------------------------------------------------------------------------------

### [前提タスク]
- 参加ゲームルーム入室確認ページ(/playgame/join_check)のページの実装

### [概要]
- 参加ゲームルーム入室確認ページ(/playgame/join_check)の処理(POSTリクエスト)を実装するタスク．

### [やること]
- [ ] GameRoomParticipantクラスのインスタンスを生成し，userID，userNameを設定する．
- [ ] PGameRoomManagerに対して生成したGameRoomParticipantを登録する．
- [ ] PGameRoomManagerクラスのbelongingフィールドに，参加者のuserID，選択した公開ゲームルームのroomIDを登録する．
- [ ] 以下に示すDoDを満たす内容の実装．

### [DoD]
- [ ] 参加者の情報が，PGameRoomManagerに登録されていること．
- [ ] 参加者情報登録の完了後，ゲームルール参加者開始前ページ(/playgame/standby)に遷移すること．

### [備考]
　~~参加者がどのルームに参加しているかは，PGameRoomManagerのフィールド publicGameRooms経由で調べられそうな気がするため，参加者情報の登録はpublicGameRoomsまたはbelongingのどちらか一方で良いかもしれない．~~

**Comment by Yura-Mp** [comment]
PGameRoomManagerクラスのbelongingフィールドに，userID - [所属の公開ゲームルームID]の登録を[やること]に追加して頂きたいです．
