### ISSUE TITLE
ゲームルーム主催者開始前ページ(/gameroom/standby)のページの実装

### ISSUE THREAD

**Issue by e1b22103** [Yura-Mp/quiz_7#57]
⇒ ※Project Status参照．
担当者: B22103
PR締め切り: 2024/12/27 23:59

--------------------------------------------------------------------------------------------

### [前提タスク]
- ゲームルーム公開前準備ページ(/gameroom/prepare_open)のPOSTリクエストに対する処理の実装

### [概要]
- 公開したゲームルームの参加状況を表示し，任意のタイミングでゲームを開始できるページのページ(画面，View)実装を行うタスク．

### [やること]
- [x] 以下に示すDoDを満たす内容の実装．

### [DoD]
- [x] PGameRoomManagerに登録されている参加者のユーザ名(GameRoomParticipant.userName)が一覧表示されること．
- [x] 該当ゲームルームについて，以下の情報が表示されること．
  - [x] ゲームルームの名前．(DB: gameRoom.roomName)
  - [x] ゲームルームの説明．(DB: gameRoom.description)
  - [x] 現在参加人数 / 最大参加人数．
- [x] [主催者]出題確認ページ(/playing/wait)に遷移する「ゲーム開始」ボタンが存在すること．
- [x] ゲームルール管理ページ(/gameroom)に遷移する「中止」ボタンが存在すること．
- [x] 「中止」ボタンを押したときに，確認のダイアログボックスが表示されること．

**Comment by Yura-Mp** [comment]
ページレイアウトに主催者のユーザ名表示の要素が欲しいです．

**Comment by Yura-Mp** [comment]
DoDに「「キャンセル」ボタンを押したときに，確認のダイアログボックスが表示されること」が追加で欲しいかもです．
