### ISSUE TITLE
ゲームルーム参加者開始前ページ(/playgame/standby)のページの実装

### ISSUE THREAD

**Issue by e1b22103** [Yura-Mp/quiz_7#58]
⇒ ※Project Status参照．
担当者: B22103
PR締め切り: 2024/12/27 23:59

--------------------------------------------------------------------------------------------

### [前提タスク]
- 参加ゲームルーム入室確認ページ(/playgame/join_check)のPOSTリクエストに対する処理の実装

### [概要]
- 参加したゲームルームの参加状況を表示し，開始まで待機するためのページのページ(画面，View)実装を行うタスク．

### [やること]
- [ ] 以下に示すDoDを満たす内容の実装．

### [DoD]
- [x] PGameRoomManagerに登録されている参加者のユーザ名(GameRoomParticipant.userName)が一覧表示されること．
- [x] 該当ゲームルームについて，以下の情報が表示されること．
  - [x] ゲームルームの名前．(DB: gameRoom.roomName)
  - [x] ゲームルームの説明．(DB: gameRoom.description)
  - [x] ホストユーザ名．
  - [x] 現在参加人数 / 最大参加人数．
- [x] 参加ゲームルール選択ページ(/playgame)に遷移する「退室」ボタンが存在すること．
- [x] 「退室」ボタンを押したときに，確認のダイアログボックスが表示されること．

**Comment by Yura-Mp** [comment]
ページレイアウトに主催者のユーザ名表示の要素が欲しいです．
